#
# Copyright 2018-2022 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Couchbase
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ github.event.inputs.jhiGenRepo }}-${{ github.event.inputs.jhiGenBranch }}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      jhiGenRepo:
        description: 'JHipster repository url'
        default: 'jhipster/generator-jhipster'
        required: false
      jhiGenBranch:
        description: 'JHipster repository branch'
        default: 'main'
        required: false

  schedule:
    - cron: '15 6 * * *'
env:
  JHI_SAMPLES: ${{ github.workspace }}/generator-jhipster/test-integration/daily-builds
jobs:
  applications:
    name: ${{ matrix.app-type }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/app
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        app-type:
          - ngx-couchbase
          - gradle-ngx-couchbase
          - webflux-couchbase
        include:
          - app-type: ngx-couchbase
            entity: couchbase
            profile: prod
            war: 0
            e2e: 1
          - app-type: gradle-ngx-couchbase
            entity: couchbase
            profile: prod
            war: 0
            e2e: 1
          - app-type: webflux-couchbase
            entity: couchbase
            profile: prod
            war: 0
            e2e: 1
    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - name: 'SETUP: Checkout jhipster-daily-builds'
        uses: actions/checkout@v4
        with:
          path: jhipster-daily-builds
      - name: 'SETUP: Checkout generator-jhipster'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.jhiGenRepo }}
          path: generator-jhipster
          ref: ${{ github.event.inputs.jhiGenBranch }}
      - uses: jhipster/actions/setup-runner@v0
        with:
          node-version: 20
          java-version: 17
          maven-cache: true
          gradle-cache: true
          binary-dir: ${{ github.workspace }}/generator-jhipster/bin
      - name: 'SETUP: environment'
        id: setup
        uses: ./generator-jhipster/.github/actions/setup
        with:
          entities-sample: ${{ matrix.entity }}
          application-sample: ${{ matrix.app-type }}
          application-environment: ${{ matrix.profile }}
          application-packaging: ${{ (matrix.war == 1 && 'war') || 'jar' }}
          enable-testcontainers: ${{ matrix.testcontainers == 1 }}
          generator-jhipster-repository: ${{ github.event.inputs.jhiGenRepo || 'https://github.com/jhipster/generator-jhipster.git' }}
          generator-jhipster-branch: ${{ github.event.inputs.jhiGenBranch || 'local' }}
      - name: 'Copy samples'
        run: cp -R "$JHI_HOME/test-integration/samples/.jhipster" "$JHI_SAMPLES"
      #----------------------------------------------------------------------
      # Install JHipster and generate project+entities
      #----------------------------------------------------------------------
      - run: npm ci --ignore-scripts
        working-directory: ${{ github.workspace }}/generator-jhipster
      - uses: jhipster/actions/build-jhipster-bom@v0
        with:
          jhipster-bom-ref: main
      - run: jhipster.cjs generate-sample daily-builds/${{ matrix.app-type }} --entities-sample ${{ matrix.entity }} --default-environment ${{ matrix.profile || 'prod' }} --sample-yorc-folder --skip-jhipster-dependencies --skip-checks --no-insight
        env:
          JHIPSTER_DEPENDENCIES_VERSION: 0.0.0-CICD
      #----------------------------------------------------------------------
      # Launch tests
      #----------------------------------------------------------------------
      - name: 'TESTS: backend'
        run: npm run ci:backend:test
      - name: 'TESTS: frontend'
        run: npm run ci:frontend:test
      - name: 'TESTS: packaging'
        run: npm run ci:e2e:package
      - name: 'TESTS: Start docker-compose containers'
        run: npm run ci:e2e:prepare
      - name: 'TESTS: End-to-End'
        run: npm run ci:e2e:run --if-present
