#
# Copyright 2018-2022 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Microservices JWT
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ github.event.inputs.jhiGenRepo }}-${{ github.event.inputs.jhiGenBranch }}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      jhiGenRepo:
        description: 'JHipster repository url'
        default: 'jhipster/generator-jhipster'
        required: false
      jhiGenBranch:
        description: 'JHipster repository branch'
        default: 'main'
        required: false
  schedule:
    - cron: '0 5 * * *'
env:
  JHI_SAMPLES: ${{ github.workspace }}/generator-jhipster/test-integration/daily-builds
jobs:
  applications:
    name: ${{ matrix.app-type }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/app
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        app-type:
          - ms-ngx-gateway-eureka
          - ms-micro-eureka
          - ms-ngx-gateway-consul
          - ms-micro-consul
          - gradle-ms-ngx-gateway-eureka
          - gradle-ms-micro-eureka
          - gradle-ms-ngx-gateway-consul
          - gradle-ms-micro-consul
        include:
          - app-type: ms-ngx-gateway-eureka
            entity: sqllight
            profile: prod
            war: 0
            e2e: 1
          - app-type: ms-micro-eureka
            entity: micro
            profile: prod
            war: 0
            e2e: 0
          - app-type: ms-ngx-gateway-consul
            entity: sqllight
            profile: prod
            war: 0
            e2e: 1
          - app-type: ms-micro-consul
            entity: micro
            profile: prod
            war: 0
            e2e: 1
          - app-type: gradle-ms-ngx-gateway-eureka
            entity: sqllight
            profile: prod
            war: 0
            e2e: 1
          - app-type: gradle-ms-micro-eureka
            entity: micro
            profile: prod
            war: 0
            e2e: 0
          - app-type: gradle-ms-ngx-gateway-consul
            entity: sqllight
            profile: prod
            war: 0
            e2e: 1
          - app-type: gradle-ms-micro-consul
            entity: micro
            profile: prod
            war: 0
            e2e: 1
    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - name: 'SETUP: Checkout jhipster-daily-builds'
        uses: actions/checkout@v4
        with:
          path: jhipster-daily-builds
      - name: 'SETUP: Checkout generator-jhipster'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.jhiGenRepo || 'jhipster/generator-jhipster' }}
          path: generator-jhipster
          ref: ${{ github.event.inputs.jhiGenBranch || 'main' }}
      - uses: jhipster/actions/setup-runner@v0
        with:
          node-version: 20
          java-version: 17
          maven-cache: true
          gradle-cache: true
          binary-dir: ${{ github.workspace }}/generator-jhipster/bin
      #----------------------------------------------------------------------
      # Install JHipster and generate project+entities
      #----------------------------------------------------------------------
      - run: npm ci --ignore-scripts
        working-directory: ${{ github.workspace }}/generator-jhipster
      - uses: jhipster/actions/build-jhipster-bom@v0
        with:
          jhipster-bom-ref: main
      - run: jhipster.cjs generate-sample daily-builds/${{ matrix.app-type }} --entities-sample ${{ matrix.entity }} --default-environment ${{ matrix.profile || 'prod' }} --sample-yorc-folder --skip-jhipster-dependencies --skip-checks --no-insight
        env:
          JHIPSTER_DEPENDENCIES_VERSION: 0.0.0-CICD
      #----------------------------------------------------------------------
      # Launch tests
      #----------------------------------------------------------------------
      - name: 'TESTS: backend'
        run: npm run ci:backend:test
      - name: 'TESTS: frontend'
        run: npm run ci:frontend:test --if-present
      - name: 'TESTS: packaging'
        run: npm run ci:e2e:package
      - name: 'TESTS: Deploying with docker-compose file'
        run: npm run ci:e2e:prepare
      - name: 'TESTS: End-to-End (Docker-compose)'
        run: npm run ci:e2e:run --if-present
